# Generated by Django 4.2.1 on 2023-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('job', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=10)),
                ('education', models.CharField(choices=[('Master', 'Master'), ('Graduate', 'Graduate'), ('Under Grad', 'Under Grad')], default='Graduate', max_length=20, null=True)),
                ('salary', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('cloud', models.BooleanField(null=True)),
                ('position', models.CharField(choices=[('Full Stack', 'Full Stack'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Testing', 'Testing'), ('Other', 'Other')], default='Frontend', max_length=20, null=True)),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('0-2 years', '0-2 years'), ('2-5 years', '2-5 years'), ('5+ years', '5+ years')], default='0-2 years', max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=50, null=True)),
            ],
        ),
    ]
