# Generated by Django 4.2.1 on 2023-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cloud',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
