# Generated by Django 4.2.1 on 2023-05-17 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate_city_alter_candidate_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='file',
            field=models.FileField(default=datetime.datetime(2023, 5, 17, 12, 21, 34, 768139, tzinfo=datetime.timezone.utc), upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(default=datetime.datetime(2023, 5, 17, 12, 21, 47, 777178, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('0-2 years', '0-2 years'), ('2-5 years', '2-5 years'), ('5+ years', '5+ years')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('Full Stack', 'Full Stack'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
