# Generated by Django 4.2.1 on 2023-05-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
