# Generated by Django 4.2.1 on 2023-05-18 12:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_candidate_file_alter_candidate_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='tech_skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('React', 'React'), ('Vue', 'Vue'), ('Angular', 'Angular'), ('Laravel', 'Laravel'), ('Springboot', 'Springboot'), ('FastAPI', 'FastAPI'), ('MongoDB', 'MongoDB'), ('Redis', 'Redis'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Golang', 'Golang'), ('Java', 'Java'), ('Docker', 'Docker'), ('GraphQL', 'GraphQL')], default='', max_length=1000),
        ),
    ]
