# Generated by Django 4.2.1 on 2023-05-29 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='employee',
            field=models.CharField(default=datetime.datetime(2023, 5, 29, 8, 42, 32, 973293, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 29, 8, 42, 37, 460334, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
