# Generated by Django 4.2.1 on 2023-05-18 13:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_candidate_tech_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='tech_skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MongoDB', 'MongoDB'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('MariaDB', 'MariaDB')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('React', 'React'), ('Vue', 'Vue'), ('Angular', 'Angular'), ('FastAPI', 'FastAPI')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Golang', 'Golang'), ('Java', 'Java'), ('C++', 'C++')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Docker', 'Docker'), ('GraphQL', 'GraphQL'), ('GIT-GITHUB', 'GIT-GITHUB'), ('Jenkins', 'Jenkins'), ('Linux', 'Linux')], default='', max_length=100),
        ),
    ]
