# Generated by Django 4.2.1 on 2023-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_email_employee_email_sent_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('chat', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.TextField(),
        ),
    ]
