# Generated by Django 4.2.1 on 2023-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_candidate_tech_skills_candidate_databases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='compnay_naot',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='app_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Hold', 'Hold'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(choices=[('Master', 'Master'), ('Graduate', 'Graduate'), ('Under Grad', 'Under Grad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('', 'Current Position'), ('Full Stack', 'Full Stack'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
