# Generated by Django 4.2.1 on 2023-05-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_candidate_compnay_naot_alter_candidate_app_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='compnay_naot',
            new_name='compnay_note',
        ),
    ]
