# Generated by Django 4.2.1 on 2023-05-20 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_compnay_naot_candidate_compnay_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2023, 5, 20, 13, 27, 35, 204042, tzinfo=datetime.timezone.utc), verbose_name='Date Of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job',
            field=models.CharField(max_length=6),
        ),
    ]
