# Generated by Django 4.2.1 on 2023-05-21 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_candidate_age_candidate_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='about_role',
            field=models.TextField(default=datetime.datetime(2023, 5, 21, 8, 58, 34, 511315, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.CharField(default=datetime.datetime(2023, 5, 21, 8, 58, 42, 547543, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(default=datetime.datetime(2023, 5, 21, 8, 58, 45, 432271, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_details',
            field=models.TextField(default=datetime.datetime(2023, 5, 21, 8, 58, 48, 551393, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_finished',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_mode',
            field=models.CharField(choices=[('Regular', 'Regular'), ('correspondence', 'correspondence'), ('Distance Learning', 'Distance Learning'), ('Online', 'Online')], default=datetime.datetime(2023, 5, 21, 8, 58, 51, 961363, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course_started',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hybrid_office',
            field=models.BooleanField(null=True, verbose_name='Remote/Office both'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution',
            field=models.CharField(default=datetime.datetime(2023, 5, 21, 8, 58, 56, 62727, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(default=datetime.datetime(2023, 5, 21, 8, 58, 59, 242875, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_at',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 8, 59, 3, 281783, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
