# Generated by Django 4.2.1 on 2023-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_candidate_about_role_candidate_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.png', upload_to='ProfileImages', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file',
            field=models.FileField(upload_to='Resumes', verbose_name='Resume'),
        ),
    ]
