# Generated by Django 4.2.1 on 2023-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_candidate_profile_image_alter_candidate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.png', upload_to='ProfileImages', verbose_name='ProfileImages'),
        ),
    ]
