# Generated by Django 4.2.1 on 2023-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_candidate_course_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='course_finished',
            field=models.DateField(auto_now_add=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='course_started',
            field=models.DateField(auto_now_add=True, verbose_name='Start Date'),
        ),
    ]
