# Generated by Django 4.2.1 on 2023-05-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_candidate_still_working_alter_candidate_about_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='compnay_note',
            new_name='company_note',
        ),
    ]
