# Generated by Django 4.2.1 on 2023-05-21 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_compnay_note_candidate_company_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='github',
            field=models.URLField(default=datetime.datetime(2023, 5, 21, 17, 47, 38, 91624, tzinfo=datetime.timezone.utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin',
            field=models.URLField(default=datetime.datetime(2023, 5, 21, 17, 47, 42, 486818, tzinfo=datetime.timezone.utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='project',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
