# Generated by Django 4.2.1 on 2023-05-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_candidate_github_candidate_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Experience', 'Experience')], max_length=20, null=True),
        ),
    ]
