# Generated by Django 4.2.1 on 2023-05-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_candidate_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='app_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Hold', 'Hold'), ('Rejected', 'Rejected')], default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.CharField(choices=[('Master', 'Master'), ('Graduate', 'Graduate'), ('Under Grad', 'Under Grad')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Experience', 'Experience')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(choices=[('', 'Current Position'), ('Full Stack', 'Full Stack'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
