# Generated by Django 4.2.1 on 2023-05-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_candidate_app_status_alter_candidate_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, default='ProfileImages/profile.png', upload_to='ProfileImages', verbose_name='ProfileImages'),
        ),
    ]
