# Generated by Django 4.2.1 on 2023-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_candidate_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='file',
            field=models.FileField(max_length=20000, upload_to='Resumes', verbose_name='Resume'),
        ),
    ]
